// CPU-pinned concurrent operation screen, never a whole-compiler timing claim.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{pathToFileURL}from'node:url';import{spawnSync}from'node:child_process';import{performance}from'node:perf_hooks';import{identity,verifyIdentity}from'../../development/workflow.mjs';
const args=process.argv.slice(2);const list=xs=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),{$:'Nil'});
function fixture(n){return'type Bit is Data:\n  On{}\n'+Array.from({length:n},(_,i)=>'def value'+i+'() -> Bit:\n  On{}\n').join('');}
if(args[0]==='worker'){
 const [,apiFile,out]=args;const api=(await import(pathToFileURL(path.resolve(apiFile)))).default;const rows=[];
 for(const n of [16,64,256]){const source=fixture(n),sources=list([{$:'FSource',name:'main',path:'/main.bend',text:source}]);const loaded=api.f_load_graph('/main.bend',sources);assert.equal(loaded.error,'');assert.equal(api.check_book(loaded.book),'');for(const workload of ['check','load-check']){const operation=()=>{const book=workload==='check'?loaded.book:api.f_load_graph('/main.bend',sources).book;return api.check_book(book);};const warm=performance.now()+80;while(performance.now()<warm)assert.equal(operation(),'');const samples=[];for(let i=0;i<3;i++){const start=performance.now();let count=0;do{assert.equal(operation(),'');count++;}while(performance.now()-start<60);samples.push({count,elapsedMs:performance.now()-start});}rows.push({n,workload,samples});}}
 fs.writeFileSync(out,JSON.stringify({kind:'phase11-choice-micro-worker',api:identity(apiFile),node:identity(process.execPath),rows,maxRssKiB:process.resourceUsage().maxRSS},null,2)+'\n');
}else{
 const [baseline,candidate,outArg]=args;const out=path.resolve(outArg);fs.mkdirSync(out,{recursive:false});fs.copyFileSync(import.meta.filename,path.join(out,'call-micro.mjs'));const inputs=[import.meta.filename,baseline,candidate,process.execPath].map(identity),report={kind:'phase11-choice-operation-screen',complete:false,pass:false,inputs,counts:[],workers:[],scope:'Actual public checking/load+check operations; fresh ABBA workers onCPU3; other jobs may run, not exclusive full-source speed.'};const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');save();
 try{
 for(const [variant,file]of [['baseline',baseline],['candidate',candidate]]){let source=fs.readFileSync(file,'utf8');for(const [name,key]of [['run_clo','closures'],['run_tail','tails']]){const needle='function '+name+'(';const at=source.indexOf(needle),open=source.indexOf('{',at);assert.ok(at>=0);source=source.slice(0,open+1)+'\n__counts.'+key+'++;'+source.slice(open+1);}source='let __counts={closures:0,tails:0};\n'+source+'\nexport function counts(){return {...__counts};} export function reset(){__counts={closures:0,tails:0};}\n';const image=path.join(out,variant+'-counted.mjs');fs.writeFileSync(image,source);const M=await import(pathToFileURL(image));for(const n of [16,64,256]){const text=fixture(n);M.reset();const loaded=M.default.f_load_graph('/main.bend',list([{$:'FSource',name:'main',path:'/main.bend',text}]));assert.equal(loaded.error,'');assert.equal(M.default.check_book(loaded.book),'');report.counts.push({variant,n,...M.counts()});}}
 for(const [index,variant]of ['baseline','candidate','candidate','baseline'].entries()){const file=variant==='baseline'?baseline:candidate,target=path.join(out,'worker-'+index+'.json'),argv=['-c','3',process.execPath,'--stack-size=4096','--max-old-space-size=4096',import.meta.filename,'worker',file,target];const result=spawnSync('taskset',argv,{encoding:'utf8',timeout:30000,maxBuffer:1024*1024});fs.writeFileSync(path.join(out,'worker-'+index+'.stdout'),result.stdout??'');fs.writeFileSync(path.join(out,'worker-'+index+'.stderr'),result.stderr??'');report.workers.push({variant,argv,status:result.status,error:result.error?.message,signal:result.signal,file:fs.existsSync(target)?identity(target):null});save();assert.equal(result.error,undefined,'Child spawn error: '+result.error?.message);assert.equal(result.signal,null,'Child terminated by signal');assert.equal(result.status,0,result.stderr);assert.ok(fs.existsSync(target),'Missing completed worker output');}
 inputs.forEach(verifyIdentity);report.inputsVerified=true;report.complete=true;report.pass=true;
 }catch(e){report.error=e.stack;process.exitCode=1;}save();console.log(JSON.stringify({complete:report.complete,pass:report.pass,counts:report.counts,error:report.error}));
}
