import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {supervise,requireExecution} from '../../development/process.mjs';
const project=path.resolve(import.meta.dirname,'../../..');const api=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]),file=path.resolve(process.argv[4]||path.join(project,'.bootstrap/upstream-phase8/tests/compile/nat_pattern_deep.bend')),expected=process.argv[5]||'306n\n',cpu=process.argv[6]||'1';fs.mkdirSync(out);
const worker=path.join(out,'worker.mjs');fs.copyFileSync(path.join(import.meta.dirname,'pattern-native-worker.mjs'),worker);
const clangRoot=path.join(project,'build/phase1/clang/root'),clang=path.join(clangRoot,'usr/bin/clang-16');const env={...process.env,BEND_TYPED_API:api,BEND_BASE:path.join(project,'dist/base.bend'),CPATH:path.join(clangRoot,'usr/include'),LIBRARY_PATH:path.join(clangRoot,'usr/lib/x86_64-linux-gnu'),LD_LIBRARY_PATH:path.join(clangRoot,'usr/lib/x86_64-linux-gnu')};
const identity=file=>({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')});
const report={kind:'phase11-actual-native-gate',started:new Date().toISOString(),pass:false,scope:'Actual checked-source native emission, Clang16 build and execution; concurrent development, no performance ratio.',cpu,node:process.version,inputs:[api,file,worker,import.meta.filename,clang,path.join(project,'tools/typed-driver.mjs'),env.BEND_BASE,path.join(project,'src/runtime/native/runtime.c')].map(identity),expected,steps:[]};const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');save();
try{
 const emit=await supervise('taskset',['-c',cpu,process.execPath,'--stack-size=4096','--max-old-space-size=4096',worker,path.join(project,'tools/typed-driver.mjs'),file,out],{env,directory:path.join(out,'emit-process'),timeoutMs:90000});report.steps.push({name:'emit',...emit});save();requireExecution(emit);const observation=JSON.parse(fs.readFileSync(path.join(out,'emission.json')));if(observation.observation.status!=='ok')throw Error('Native emission failed');report.emission=observation;report.source=identity(path.join(out,'program.c'));
 const binary=path.join(out,'program');const build=await supervise('taskset',['-c',cpu,clang,'-std=c11','-O3',path.join(out,'program.c'),'-lpthread','-lm','-o',binary],{env,directory:path.join(out,'build-process'),timeoutMs:90000});report.steps.push({name:'build',...build});save();requireExecution(build);
 const run=await supervise('taskset',['-c',cpu,binary],{env,directory:path.join(out,'run-process'),timeoutMs:10000});report.steps.push({name:'run',...run});save();requireExecution(run);report.stdout=fs.readFileSync(run.stdout,'utf8');report.stderr=fs.readFileSync(run.stderr,'utf8');if(report.stdout!==expected)throw Error('Unexpected native stdout');for(const before of report.inputs)if(identity(before.file).sha256!==before.sha256)throw Error('Input identity changed');report.pass=true;
}catch(error){report.error=String(error.stack??error);process.exitCode=1;}report.finished=new Date().toISOString();save();console.log(JSON.stringify({pass:report.pass,error:report.error,layout:report.emission?.layout}));
