import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const project=path.resolve(import.meta.dirname,'../../..'),out=path.resolve(process.argv[2]);fs.mkdirSync(out);const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const list=xs=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),{$:'Nil'}),term=(tag,name='',kids=[])=>({$:'KTerm',tag,name,id:0,quant:1,kids:list(kids),removed:list([])}),def=(name,kind,typ=term('Typ'),ctors=[],native=false,value=term('Absent'))=>({$:'KDef',name,kind,arity:0,templates:0,typ,value,ctors:list(ctors),native,unsafe:false});
const aCtor=def('Make','Ctr',term('ADT','A')),bCtor=def('Other','Ctr',term('ADT','B')),book=list([def('A','ADT',term('Typ'),[aCtor]),def('B','ADT',term('Typ'),[bCtor])]);
const cases=[['local',book,term('ADT','A'),'Make'],['other-family-fallback',book,term('ADT','B'),'Make'],['absent-family-fallback',book,term('ADT','Missing'),'Make'],['non-ADT-fallback',book,term('Typ','A'),'Make'],['missing-constructor',book,term('ADT','A'),'Absent'],['empty-book',list([]),term('ADT','A'),'Make']];
const duplicate=def('Make','Ctr',term('ADT','Wrong'));cases.push(['unchecked-duplicate-counterexample',list([def('Wrong','ADT',term('Typ'),[duplicate]),def('A','ADT',term('Typ'),[aCtor])]),term('ADT','A'),'Make']);
const variants={baseline:path.join(project,'build/phase9/integrated-03/equality/api.mjs'),candidate:path.join(project,'build/phase10/layout-combined-01/attempt/equality/api.mjs')},apis={},inputs=[];
for(const [name,file] of Object.entries(variants)){const raw=fs.readFileSync(file,'utf8'),extra=name==='baseline'?'export const probe=(book,ty,name)=>run_loop($j_find_ctor$(book,name));':'export const probe=(book,ty,name)=>run_loop($j_layout_ctor$(book,ty,name));\nexport const nativeNat=(book,t,ty)=>run_loop($j_layout_native_nat$(book,t,ty));';const derived=path.join(out,name+'.mjs');fs.writeFileSync(derived,raw+'\n'+extra+'\n');inputs.push({name,file,sha256:hash(raw),derived,derivedSha256:hash(fs.readFileSync(derived))});apis[name]=await import(pathToFileURL(derived));}
const rows=cases.map(([name,book,ty,ctor])=>{const baseline=apis.baseline.probe(book,ty,ctor),candidate=apis.candidate.probe(book,ty,ctor),same=JSON.stringify(baseline)===JSON.stringify(candidate),expectedSame=name!=='unchecked-duplicate-counterexample';assert.equal(same,expectedSame,name);return{name,book,ty,ctor,baseline,candidate,same,expectedSame}});
const natBook=list([def('Nat','ADT',term('Typ'),[],true)]),customBook=list([def('Nat','ADT')]);const guards=[['native-zero',natBook,term('Ctr','Zero'),term('ADT','Nat'),true],['native-succ',natBook,term('Ctr','Succ',[term('Var','tail')]),term('ADT','Nat'),true],['custom-nat',customBook,term('Ctr','Zero'),term('ADT','Nat'),false],['wrong-type',natBook,term('Ctr','Zero'),term('ADT','Other'),false],['other-ctor',natBook,term('Ctr','Other'),term('ADT','Nat'),false],['bad-zero-arity',natBook,term('Ctr','Zero',[term('Var','x')]),term('ADT','Nat'),false],['bad-succ-arity',natBook,term('Ctr','Succ'),term('ADT','Nat'),false],['bad-succ-extra',natBook,term('Ctr','Succ',[term('Var','x'),term('Var','y')]),term('ADT','Nat'),false]];
const guardRows=guards.map(([name,book,t,ty,expected])=>{const actual=apis.candidate.nativeNat(book,t,ty);assert.equal(actual,expected,name);return{name,book,t,ty,expected,actual}});
fs.writeFileSync(path.join(out,'report.json'),JSON.stringify({scope:'Disposable views of checked images; malformed duplicate-book counterexample deliberately demonstrates the checked-source uniqueness boundary.',inputs,pass:true,rows,guardRows},null,2)+'\n');console.log(JSON.stringify({pass:true,equivalentFallbackControls:6,expectedDuplicateCounterexamples:1,nativeGuardControls:8}));
