import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {supervise,requireExecution} from '../../development/process.mjs';
const project=path.resolve(import.meta.dirname,'../../..'),candidate=path.resolve(process.argv[2]),out=path.resolve(process.argv[3]),cpu=process.argv[4]||'0';fs.mkdirSync(out);
const file=path.join(project,'.bootstrap/upstream-phase8/tests/compile/nat_pattern_deep.bend'),driver=path.join(project,'tools/typed-driver.mjs'),worker=path.join(out,'worker.mjs'),prepare=path.join(out,'prepare.mjs');fs.copyFileSync(path.join(import.meta.dirname,'layout-control-worker.mjs'),worker);fs.writeFileSync(prepare,`import {pathToFileURL} from 'node:url';const {loadApi,prepareBase}=await import(pathToFileURL(process.argv[2]));await prepareBase(await loadApi());\n`);
const variants={baseline:path.join(project,'build/phase9/integrated-03/equality/api.mjs'),candidate};const identity=file=>({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')});const env=api=>({...process.env,BEND_TYPED_API:api,BEND_BASE:path.join(project,'dist/base.bend')});
const report={kind:'Nat300-fresh-process-ABBA',pass:false,started:new Date().toISOString(),scope:'Serial fresh processes on one CPU; compileMs includes public JS workflow through emitted code; process wall also includes import/startup and actual emitted program execution. Per-variant validated disk Base cache is explicitly prepared before timing. Other intentional compiler jobs must be paused by caller; OS cache not flushed.',node:process.version,cpu,resources:{stackKiB:4096,heapMiB:4096,deadlineMs:90000},preparation:[],inputs:[...new Set([...Object.values(variants),file,driver,worker,prepare,import.meta.filename,process.execPath,path.join(project,'dist/base.bend'),path.join(project,'src/runtime.mjs')])].map(identity),rows:[]};const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');save();
try{
 for(const [name,api]of Object.entries(variants)){const result=await supervise('taskset',['-c',cpu,process.execPath,'--stack-size=4096','--max-old-space-size=4096',prepare,driver],{env:env(api),directory:path.join(out,'prepare-'+name),timeoutMs:90000});report.preparation.push({name,...result});save();requireExecution(result);}
 for(const [index,name]of ['baseline','candidate','candidate','baseline'].entries()){const directory=path.join(out,index+'-'+name);fs.mkdirSync(directory);const request={name:'nat-300',file,directory,driver,expectedStatus:'ok',stdout:'306n\n'};const requestFile=path.join(directory,'request.json');fs.writeFileSync(requestFile,JSON.stringify(request,null,2)+'\n');const execution=await supervise('taskset',['-c',cpu,process.execPath,'--stack-size=4096','--max-old-space-size=4096',worker,requestFile],{env:env(variants[name]),directory:path.join(directory,'process'),timeoutMs:90000});const row={index,name,execution,result:fs.existsSync(path.join(directory,'result.json'))?JSON.parse(fs.readFileSync(path.join(directory,'result.json'))):null};report.rows.push(row);save();requireExecution(execution);if(!row.result.pass)throw Error('Case gate failed');}
 if(new Set(report.rows.map(x=>x.result.codeSha256)).size!==1)throw Error('Emitted code changed');for(const x of report.inputs)if(identity(x.file).sha256!==x.sha256)throw Error('Input changed: '+x.file);report.means=Object.fromEntries(Object.keys(variants).map(name=>{const rows=report.rows.filter(x=>x.name===name);return[name,{compileMs:rows.reduce((s,x)=>s+x.result.compileMs,0)/rows.length,layoutMs:rows.reduce((s,x)=>s+x.result.layout.ms,0)/rows.length,processMs:rows.reduce((s,x)=>s+x.execution.wallMs,0)/rows.length}]}));report.pass=true;
}catch(error){report.error=String(error.stack??error);process.exitCode=1;}report.finished=new Date().toISOString();save();console.log(JSON.stringify({pass:report.pass,means:report.means,error:report.error}));
