// Experimental branch-block derivative of verified v4 generated B1; not production.
import assert from'node:assert/strict';import{createHash}from'node:crypto';import{tokens}from'../phase11/call-choice.mjs';
const sha=s=>createHash('sha256').update(s).digest('hex'),marker='// Program\n// =======\n',runtime='241696c207b257ba28e159699e08e749c1625542a92d901a663ac3f04dfd20fd';
export function transformTailChoices(source){
 const start=source.indexOf(marker)+marker.length;assert.ok(start>=marker.length);assert.equal(sha(source.slice(0,start)),runtime,'Unsupported runtime');const ts=tokens(source,start),functions=new Map();let at=0;
 while(ts[at]?.text==='function'){const first=at,name=ts[at+1].text;assert.match(name,/^\$[\w$]+\$$/);assert.ok(!functions.has(name),'Duplicate generated binding');assert.equal(ts[at+2].text,'(');const body=ts[at+2].close+1;assert.equal(ts[body].text,'{');functions.set(name,{first,body,end:ts[body].close});at=ts[body].close+1;}
 assert.equal(ts[at]?.text,'export');assert.equal(ts[at+1]?.text,'default');assert.equal(ts[at+2]?.text,'{');assert.equal(ts[at+2].close,ts.length-2);assert.equal(ts.at(-1).text,';');
 const protectedNames=new Set([...functions.keys(),'run_tail','run_loop','run_clo','run_lib']);
 for(let i=0;i<ts.length;i++){const t=ts[i].text,prev=ts[i-1]?.text,next=ts[i+1]?.text;assert.ok(!['this','arguments','super','new','eval','function*','yield','await','try','finally'].includes(t),'Unsupported lexical/control dependency');if(t==='function')assert.equal(functions.get(ts[i+1]?.text)?.first,i,'Nested function');let params;if(t==='function')params=i+2;else if(t==='('&&ts[ts[i].close+1]?.text==='='&&ts[ts[i].close+2]?.text==='>')params=i;if(params!==undefined){assert.equal(ts[params]?.text,'(');assert.ok(!ts.slice(params+1,ts[params].close).some(x=>protectedNames.has(x.text)),'Protected parameter');}if(!protectedNames.has(t))continue;assert.ok(!['let','const','var'].includes(prev)&&next!=='='&&!(['+','-','*','/','&','|','^','?'].includes(next)&&['=',next].includes(ts[i+2]?.text)),'Rebound protected name');if(prev!=='function')assert.ok(next==='('&&!['.','new'].includes(prev),'Unsupported protected reference');}
 const split=open=>{const out=[];let lo=open+1;for(let i=lo;i<ts[open].close;i++){if(ts[i].close!==undefined){i=ts[i].close;continue;}if(ts[i].text===','){out.push([lo,i]);lo=i+1;}}if(lo<ts[open].close)out.push([lo,ts[open].close]);return out;};
 const strip=([lo,hi])=>{while(ts[lo]?.text==='('&&ts[lo].close===hi-1){lo++;hi--;}return[lo,hi];};
 const semicolon=(lo,hi)=>{for(let i=lo;i<hi;i++){if(ts[i].close!==undefined){i=ts[i].close;continue;}if(ts[i].text===';')return i;}return-1;};
 const branch=range=>{const[lo,hi]=strip(range);if(ts[lo]?.text!=='('||ts[lo].close!==lo+2||!/^[A-Za-z_$][\w$]*$/.test(ts[lo+1]?.text??'')||ts[lo+3]?.text!=='='||ts[lo+4]?.text!=='>'||ts[lo+5]?.text!=='{'||ts[lo+5].close!==hi-1)return null;const body=lo+5,end=hi-1,param=ts[lo+1].text;let i=body+1;while(ts[i]?.text==='const'){if(!/^[A-Za-z_$][\w$]*$/.test(ts[i+1]?.text??'')||ts[i+2]?.text!=='=')return null;const stop=semicolon(i+3,end);if(stop<0)return null;i=stop+1;}if(ts[i]?.text!=='return'||semicolon(i+1,end)!==end-1)return null;return{body,end,param,ret:i,expr:[i+1,end-1]};};
 const sites=new Map(),skipped=[];for(let i=0;i<at;i++){if(ts[i].text!=='return'||ts[i+1]?.text!=='run_tail'||ts[i+2]?.text!=='('||ts[ts[i+2].close+1]?.text!==';')continue;const args=split(i+2);if(args.length!==2)continue;const[lo,hi]=args[0],q=ts[lo]?.close+1;if(ts[lo]?.text!=='('||ts[q]?.text!=='?')continue;const yesStart=q+1,colon=ts[yesStart]?.close+1;if(ts[yesStart]?.text!=='('||ts[colon]?.text!==':')continue;const noStart=colon+1;if(ts[noStart]?.text!=='('||ts[noStart].close!==hi-1)continue;const unit=ts.slice(...args[1]).map(x=>x.text).join('');if(unit!=='{$:"Unit"}')continue;const yes=branch([yesStart,colon]),no=branch([noStart,hi]);if(!yes||!no){skipped.push({at:ts[i].start,reason:'Non-const/return branch'});continue;}sites.set(i,{end:ts[i+2].close+2,condition:[lo,q],yes,no});}
 let deferred=0;const renderBranch=b=>{let text='const '+b.param+' = {$: "Unit"};\n'+render(b.body+1,b.ret);const[lo,hi]=strip(b.expr);if(functions.has(ts[lo]?.text)&&ts[lo+1]?.text==='('&&ts[lo+1].close===hi-1){deferred++;const args=split(lo+1).map(a=>render(...a));return text+'return {$: "$JMP", f: '+ts[lo].text+', x: ['+args.join(', ')+']};';}return text+render(b.ret,b.end);};
 const render=(lo,hi)=>{if(lo===hi)return'';let text='',cursor=ts[lo].start;for(let i=lo;i<hi;i++){const site=sites.get(i);if(!site||site.end>hi)continue;text+=source.slice(cursor,ts[i].start)+'if ('+render(...site.condition)+') {\n'+renderBranch(site.yes)+'\n} else {\n'+renderBranch(site.no)+'\n}';cursor=ts[site.end-1].end;i=site.end-1;}return text+source.slice(cursor,ts[hi-1].end);};
 const program=source.slice(0,start)+source.slice(start,ts[0].start)+render(0,ts.length)+source.slice(ts.at(-1).end);return{source:program,report:{kind:'return-choice-block-derivative',version:1,sites:sites.size,deferredGeneratedCalls:deferred,skipped,runtimeSha256:runtime,inputSha256:sha(source),outputSha256:sha(program),scope:'Only returned literal Unit choices with const/return bodies. Terminal direct generated calls defer through the unchanged runtime; public wrappers and runtime stay exact. Private unforced tail-message representation is not an invariant.'}};
}
