#!/usr/bin/env python3
from pathlib import Path
import json,hashlib,shutil,difflib
ROOT=Path(__file__).resolve().parents[4];BASE=ROOT/'selfhost/build/phase16/alias-binding-source-04/project';OUT=ROOT/'selfhost/build/phase16/alias-pattern-source-02';OUT.mkdir();shutil.copytree(BASE,OUT/'project');p=OUT/'project/src/front/elaborate.bend';s=p.read_text();a='''Con{f_choose(KTerm, f_choose(Bool, f_eq(tg(x), "Ref"), u => True{}, u => f_choose(Bool, f_eq(tg(x), "FAliasRef"), u => Bool.not(f_eq(tg(f_env(nm(x), env)), "Absent")), u => False{})), u => kt_span("Var", nm(x), ix(x), qt(x), Nil{}, kb(x), ke(x)), u => f_choose(KTerm, f_eq(tg(x), "FAliasRef"), u => kid(x, 0), u => f_choose(KTerm, f_eq(tg(x), "Literal"), u => f_span_created(f_pattern_literal(nm(x)), kb(x), ke(x)), u => f_choose(KTerm, f_eq(tg(x), "Ctr"), u => k_with_children(x, f_patterns(ks(x), env)), u => x)))), f_patterns(xt, env)}''';b='''Con{f_choose(KTerm, f_eq(tg(x), "Ref") || f_eq(tg(x), "FAliasRef"), u => f_pattern_reference(x, env), u => f_choose(KTerm, f_eq(tg(x), "Literal"), u => f_span_created(f_pattern_literal(nm(x)), kb(x), ke(x)), u => f_choose(KTerm, f_eq(tg(x), "Ctr"), u => k_with_children(x, f_patterns(ks(x), env)), u => x))), f_patterns(xt, env)}''';assert s.count(a)==1;s=s.replace(a,b);at=s.index('@unsafe\ndef f_scope_local(');s=s[:at]+'''# A qualified spelling is a binder only when parse_var would find it in scope.
@unsafe
def f_pattern_reference(+t: KTerm, +env: List<&2,KTerm>) -> KTerm:
  f_choose(KTerm, f_choose(Bool, String.contains(nm(t), "."), u => Bool.not(f_eq(tg(f_env(nm(t), env)), "Absent")), u => True{}),
    u => kt_span("Var", nm(t), ix(t), qt(t), Nil{}, kb(t), ke(t)),
    u => f_choose(KTerm, f_eq(tg(t), "FAliasRef"), u => kid(t, 0), u => t))

'''+s[at:];p.write_text(s);old=BASE/'src/front/elaborate.bend';x=old.read_text();(OUT/'elaborate.patch').write_text(''.join(difflib.unified_diff(x.splitlines(True),s.splitlines(True),fromfile='parent/src/front/elaborate.bend',tofile='candidate/src/front/elaborate.bend')));manifest={'complete':True,'parent':str(BASE),'plan':'experiments/phase16/P16-qualified-pattern-bindings.md','changes':[{'file':'src/front/elaborate.bend','beforeSha256':hashlib.sha256(old.read_bytes()).hexdigest(),'afterSha256':hashlib.sha256(p.read_bytes()).hexdigest(),'lineDelta':len(s.splitlines())-len(x.splitlines()),'byteDelta':len(p.read_bytes())-len(old.read_bytes())}]};(OUT/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n');cfg=json.loads((BASE.parent/'workflow.json').read_text());cfg['project']=str(OUT/'project');(OUT/'workflow.json').write_text(json.dumps(cfg,indent=2)+'\n');shutil.copy2(__file__,OUT/Path(__file__).name);print(OUT)
