from pathlib import Path
import sys,shutil,json,hashlib,difflib
root=Path.cwd();base=root/'selfhost';old=Path(sys.argv[1]).resolve();out=Path(sys.argv[2]).resolve();out.mkdir();project=out/'project';shutil.copytree(old,project)
helper=root/'selfhost/tools/performance/phase16/checker-key-json.bend';p=project/'src/check/specialize.bend';s=p.read_text();assert 'def k_quantity_present(' in (project/'src/core/term.bend').read_text()
a=s.index('@unsafe\ndef sp_len(');b=s.index('@unsafe\ndef sp_find(',a);s=s[:a]+helper.read_text()+'\n'+s[b:];law='law sp_name_keys:\n  for +ns: List<&2, String>\n  String\n\n';assert s.count(law)==1;s=s.replace(law,'');p.write_text(s)
p=project/'tools/typed-driver.mjs';s=p.read_text();needle='const exports=[...roots];';assert s.count(needle)==1;s=s.replace(needle,needle+"\n  exports.push('term_key','sp_keys','sp_len','sk_quote');");p.write_text(s)
changes=[];patch=[]
for name in ['src/check/specialize.bend','tools/typed-driver.mjs']:
 before=(old/name).read_bytes();after=(project/name).read_bytes();changes.append({'file':name,'beforeSha256':hashlib.sha256(before).hexdigest(),'afterSha256':hashlib.sha256(after).hexdigest(),'physicalLineDelta':len(after.splitlines())-len(before.splitlines()),'byteDelta':len(after)-len(before)});patch.append(''.join(difflib.unified_diff(before.decode().splitlines(True),after.decode().splitlines(True),fromfile='a/'+name,tofile='b/'+name)))
(out/'combined.patch').write_text(''.join(patch));(out/'manifest.json').write_text(json.dumps({'kind':'phase16-canonical-memo-json','parent':str(old),'changes':changes,'toolSha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'helper':{'file':str(helper),'sha256':hashlib.sha256(helper.read_bytes()).hexdigest()},'plan':{'file':str(root/'design/phase16/checker-canonical-memo-json.md'),'sha256':hashlib.sha256((root/'design/phase16/checker-canonical-memo-json.md').read_bytes()).hexdigest()},'installationEligible':False,'probeOnlyExports':['term_key','sp_keys','sp_len','sk_quote']},indent=2)+'\n');(out/'config.json').write_text(json.dumps({'project':str(project),'upstream':str(base/'.bootstrap/upstream-phase8'),'profile':'equality','cpu':'1','jobs':1},indent=2)+'\n');print(out)
