from pathlib import Path
import json,hashlib,re
root=Path.cwd();b=root/'selfhost/build/phase16';source=b/'checker-literal-source-05/project';parent=b/'wave6-source-01/project'
def read(p):return json.loads(p.read_text())
def ident(p):return {'file':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
def counts(p):
 files=read(p/'src/compiler.json')['modules'];s=''.join((p/f).read_text() for f in files);return {'modules':len(files),'physicalLines':len(s.splitlines()),'nonblankLines':sum(bool(l.strip()) for l in s.splitlines()),'bytes':len(s.encode()),'definitions':len(re.findall(r'^def ',s,re.M)),'laws':len(re.findall(r'^law ',s,re.M)),'types':len(re.findall(r'^type ',s,re.M))}
old=read(b/'checker-base-prefix-serial-01/report.json')['rows'][0]['result'];new=read(b/'checker-literal-compact-census-02/result.json');assert old['output']['definitions']==new['serialized']['definitions']==2894;assert old['outputCensus']['definitions']==new['loaded']['definitions']==3015;assert old['outputCensus']['locatedTerms']==new['loaded']['locatedTerms']==150871
sourceId=read(b/'stage-matrix-01/report.json')['source'];assert sourceId['sha256']=='f90cfb97987b4a0f13311ac368eb179c2f77439ae9650cec200f12df10220380'
for q in [b/'checker-base-prefix-serial-01/report.json',b/'checker-literal-compact-census-02/report.json']:
 d=read(q);assert any(i['file']==sourceId['file'] and i['sha256']==sourceId['sha256'] for i in d['inputs'])
report={'kind':'phase16-compact-literal-checkpoint','status':'representation correctness supported; promotion blocked pending canonical memo keys and root integration','source':str(source),'parent':str(parent),'handoff':ident(b/'checker-literal-handoff-01/manifest.json'),'api':ident(b/'checker-literal-build-05/equality/api.mjs'),'sourceCost':{'before':counts(parent),'after':counts(source)},'gates':{},'sameSourceCensus':{'source':sourceId,'boundary':'Final freshened loaded book. Earlier serial full arm explicitly validates and freshens; new public seeded loader executes that same successful validation/freshening path. Same checked Base pin and source graph.','serialization':'Exact full named-field linked Con/Nil JSON using identical bookDigest framing; not the newline stream from compact-census01.','baseline':old['outputCensus'],'candidate':new['loaded'],'baselineSerialized':old['output'],'candidateSerialized':new['serialized'],'termReductionFraction':1-new['loaded']['terms']/old['outputCensus']['terms'],'objectReductionFraction':1-new['loaded']['objects']/old['outputCensus']['objects'],'serializedByteReductionFraction':1-new['serialized']['bytes']/old['output']['bytes'],'checked':new['checkError']=='','timingClaim':False},'memo':read(b/'checker-literal-memo-02/report.json'),'failures':[{'attempt':'checker-literal-source-02','kind':'pre-build static rejection','reason':'Preparation wrapper misplaced three closing parentheses after following law declarations; preserved and corrected in03.'},{'attempt':'checker-literal-source-04','kind':'preparation assertion','reason':'Requested nonexistent g_normalize probe export; no host edit/build; corrected05.'},{'attempt':'checker-literal-backend-05','kind':'environment incomplete','reason':'12native observations unsupported in both compilers because Clang missing from default environment;29other exact. CorrectClangenv rerun07 closes41.'},{'attempt':'checker-literal-backend-06','kind':'setup metadata validation','reason':'Historical environment file records lack canonicalPath; strict full identity reader rejected unchanged Node before job. Tool02 checks supplied SHA/optional canonical path.'},{'attempt':'checker-literal-memo-01','kind':'invalid prospective fixture/tool diagnostic limitation','reason':'Pinned source has no unary(-0.0). Probe stopped after3valid rows; catch assumed Error.stack, hiding structuredBendErr. Freshcontrols03/tool02 useF32.neg and retain structured failures.'}], 'openWork':['Consolidated termABI1/cachev6 and explicit KLambda quantity presence owned by representation agent.','One exact pinned JSON key supplies memo identity and32768UTF16 guard; replaces position-sensitive shortencoding.','Production handoff removes probe exports; root must build/gate integrated union.','Exact Phase12 request-history replay, full frontend/backend integration and exclusive same-source timing.'],'inputs':[]}
for name,loc in [('representation48','checker-literal-transport-01/report.json'),('maintained36','checker-literal-build-05/validation-001/report.json'),('literal176','checker-literal-focus-05/report.json'),('direct143','checker-literal-direct-01/report.json'),('host31','checker-literal-host-01/report.json'),('backend41','checker-literal-backend-07/report.json')]:
 p=b/loc;d=read(p);assert d['complete'] and d['pass'];report['gates'][name]={'report':ident(p),'complete':True,'pass':True,'exactDifferences':d.get('selected',{}).get('exactDifferences'), 'rows':len(d.get('rows',[])) or d.get('selected',{}).get('candidate',{}).get('probes')};report['inputs'].append(ident(p))
report['inputs'] += [ident(b/'checker-base-prefix-serial-01/report.json'),ident(b/'checker-literal-compact-census-02/report.json'),ident(b/'checker-literal-memo-02/report.json'),ident(Path(__file__).resolve())]
(root/'implementation/phase16/checker-compact-literals.json').write_text(json.dumps(report,indent=2)+'\n')
print(json.dumps({k:report['sameSourceCensus'][k] for k in ['termReductionFraction','objectReductionFraction','serializedByteReductionFraction']}))
