from pathlib import Path
import json, hashlib, re
root=Path.cwd();phase=root/'selfhost/build/phase16'
def ident(p):
 b=p.read_bytes();return {'file':str(p),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)}
def read(name):return json.loads((phase/name).read_text())
direct=read('checker-key-json-direct-02/report.json');instances=read('checker-key-json-instances-02/report.json');growth=read('checker-key-json-growth-01/selected/paired.json')
assert direct['complete'] and direct['pass'] and len(direct['rows'])==61
assert instances['complete'] and instances['pass'] and len(instances['rows'])==29
assert growth['complete'] and len(growth['rows'])==2 and all(x['exactAgreement'] for x in growth['rows'])
locations=[]
for row in growth['rows']:
 d=row['candidate']['diagnostic'];locations.append({'id':row['id'],'location':re.search(r'Location: ([^\n]+)',d).group(1),'exact':True})
assert sorted(x['location'] for x in locations)==['grow~63','grow~9']
def counts(p):
 s=p.read_text();return {'physicalLines':len(s.splitlines()),'nonblankLines':sum(bool(x.strip()) for x in s.splitlines()),'bytes':p.stat().st_size,'definitions':len(re.findall(r'^def ',s,re.M)),'laws':len(re.findall(r'^law ',s,re.M))}
before=counts(phase/'spans-lambda-source-03/project/src/check/specialize.bend');after=counts(phase/'checker-key-json-source-02/project/src/check/specialize.bend')
paths=['checker-key-json-source-01/manifest.json','checker-key-json-build-01/attempt.json','checker-key-json-direct-01/report.json','checker-key-json-instances-01/report.json','checker-key-json-source-02/manifest.json','checker-key-json-build-02/attempt.json','checker-key-json-direct-02/report.json','checker-key-json-instances-02/report.json','checker-key-json-growth-01/report.json','checker-key-json-growth-01/selected/paired.json','checker-key-json-handoff-01/manifest.json','checker-key-json-handoff-01/memo.patch','checker-key-json-handoff-01/combined.patch','checker-key-json-controls-01/direct.json','checker-key-json-growth-controls-01/selection.json']
report={'kind':'phase16-canonical-template-memo-json','complete':True,'ownedScopedGatesPass':True,'installed':False,'design':ident(root/'design/phase16/checker-canonical-memo-json.md'),'inputs':[ident(phase/p) for p in paths],'implementation':{'module':'src/check/specialize.bend','encoding':'Exact pinned term_key(term_lower(argument)) JSON bytes for parsed-source semantic terms; same string defines memo identity and32768 UTF16 growth guard.','newRuntimeTypes':0,'newCacheFormats':0,'representationDependency':'Metadata owner KLambda explicit quantity presence and compiler_term_abi1/cache6; final handoff includes source04 demand semantics.','memoSourceSha256':ident(phase/'checker-key-json-handoff-01/project/src/check/specialize.bend')['sha256']},'gates':{'checkedBuild':'checker-key-json-build-02 genuine checked B1 and equality derivative; maintained36 pass,2 inherited exact diagnostic differences','directExact':{'passed':61,'sizeBoundariesIncluded':20},'parsedInstancesExact':{'passed':29},'growthExact':locations},'preservedAttempt01':{'checked':True,'directExact':61,'parsedExact':28,'parsedTotal':29,'failure':'Absent-versus-explicit Lambda collided because f_scope_lambda_var reconstructed presence as true. Metadata source03 fixes this; source02 encoder gates all pass.'},'sourceCost':{'before':before,'after':after,'delta':{k:after[k]-before[k] for k in before},'probeOnlyHostLineRemovedInHandoff':True},'operationCost':'One canonical JSON serialization per closed template argument plus a tail-safe UTF16 length walk over the joined key. No second approximate encoding/count, no new whole-book pass. No isolated timing claim.','handoff':{'directory':str(phase/'checker-key-json-handoff-01'),'productionHost':'Metadata source04 host unchanged; four probe exports absent','unionBuildPendingRoot':True},'limitations':['Scoped gates do not infer full-corpus or backend conformance; root owns final union checks and controlled timing.','Term-level specialization chronology is unchanged; the existing same-body priority gap is separate.','Explicit Ref.b=false exists in the raw TypeScript factory but no pinned parsed-source producer constructs it; current core supports source-reachable absent/true flags.','Malformed internal-only terms have a distinct defensive JSON shape, outside parsed-source memo equivalence.']}
out=root/'implementation/phase16/checker-canonical-memo-json.json';out.write_text(json.dumps(report,indent=2)+'\n');print(out)
