from pathlib import Path
import shutil,json,hashlib,difflib
R=Path(__file__).resolve().parents[4];base=R/'selfhost/build/phase16/spans-import-source-03/project';out=R/'selfhost/build/phase16/spans-import-source-04';out.mkdir();p=out/'project';shutil.copytree(base,p);file=p/'src/front/parser.bend';old=file.read_text();new=old
needle='u => "\'" ++ SCon{fpe_utf16_char(c, offset), ""} ++ "\'",';assert new.count(needle)==1;new=new.replace(needle,'u => f_choose(String, U32.is_le(Char.to_u32(c), 65535), u => "\'" ++ SCon{c, ""} ++ "\'", u => ""),')
a=new.index('@unsafe\ndef fpe_utf16_char(');b=new.index('@unsafe\ndef fpe_snippet(',a);new=new[:a]+new[b:]
needle='u => "Error:\\n- expected : " ++ nm(kid(error, 0)) ++ "\\n- observed : " ++ f_choose(String, f_eq(tg(kid(error, 1)), "ParseObservedPoint"), u => fpe_point_observed(source, U32.sub(kb(error), start)), u => nm(kid(error, 1))) ++ "\\nLocation:" ++ fpe_snippet(source, U32.sub(kb(error), start), U32.sub(ke(error), start), error)'
assert new.count(needle)==1
new=new.replace(needle,'u => fpe_point_message(source, U32.sub(kb(error), start), U32.sub(ke(error), start), error, f_choose(String, f_eq(tg(kid(error, 1)), "ParseObservedPoint"), u => fpe_point_observed(source, U32.sub(kb(error), start)), u => nm(kid(error, 1))))')
new+='''\n# UTF16 surrogate halves cannot be manufactured as Bend Unicode scalar chars.\n# Keep the producer's legacy diagnostic on that boundary instead of crashing.\n@unsafe\ndef fpe_point_message(+source: String, +begin: U32, +end: U32, +error: KTerm, +observed: String) -> String:\n  f_choose(String, f_eq(tg(kid(error, 1)), "ParseObservedPoint") && String.is_empty(observed),\n    u => nm(error), u => fpe_message(source, begin, end, error, observed))\n'''
file.write_text(new);shutil.copy2(__file__,out/Path(__file__).name);(out/'workflow.json').write_text(json.dumps({'project':str(p),'upstream':str(R/'selfhost/.bootstrap/upstream-phase8'),'cpu':'2','jobs':1,'profile':'equality','timeoutMs':30000},indent=2)+'\n');(out/'parser.patch').write_text(''.join(difflib.unified_diff(old.splitlines(True),new.splitlines(True),fromfile='a/src/front/parser.bend',tofile='b/src/front/parser.bend')));(out/'manifest.json').write_text(json.dumps({'parent':str(base),'project':str(p),'reason':'Independent astral-point controls exposed invalid surrogate construction; preserve conservative legacy failure on unrepresentable point observations, with no runtime semantic change.','before':hashlib.sha256(old.encode()).hexdigest(),'after':hashlib.sha256(new.encode()).hexdigest()},indent=2)+'\n')
