// Phase22 production parser: original broader196 remains a strict differential oracle.
// Acquisition completeness is audited separately from historical expected labels.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const root=path.resolve(import.meta.dirname,'../../../..'),build=fs.realpathSync(process.argv[2]),out=path.resolve(process.argv[3]),selection=fs.realpathSync(process.argv[4]);
const workflow=path.join(build,'snapshot/tools/development/workflow.mjs'),processFile=path.join(build,'snapshot/tools/development/process.mjs'),w=await import(pathToFileURL(workflow)),{supervise,requireExecution}=await import(pathToFileURL(processFile)),m=await w.verifyAttempt(build);
const env={...process.env};for(const k of Object.keys(env))if(k.startsWith('BEND_')||['NODE_OPTIONS','NODE_PATH'].includes(k))delete env[k];Object.assign(env,{BEND_UPSTREAM:m.config.upstream,BEND_BASE:m.base.file,BEND_TYPED_API:m.api.file,BEND_TYPED_RUNTIME:m.runtime.file,BEND_TYPED_TRACE:''});
const cache=w.validatedCache(path.join(m.snapshot.root,'build/typed/cache'),m.api.file,m.base.file);fs.mkdirSync(out);fs.copyFileSync(import.meta.filename,path.join(out,'consumed-tool.mjs'));
const data=JSON.parse(fs.readFileSync(selection)),cases=Array.isArray(data)?data:data.cases;assert.ok(cases.length);fs.writeFileSync(path.join(out,'selection.json'),JSON.stringify({cases},null,2)+'\n');
const target={upstream:m.config.upstream,selection:path.join(out,'selection.json'),jobs:1,workerMode:cases.every(c=>c.lanes.every(l=>['parse','check'].includes(l)))?'persistent':'isolated',recycleAfter:64,rssLimitMb:4096,heapMb:4096,stackKb:4096,timeoutMs:120000,retain:'failed',candidateAdapter:path.join(m.snapshot.root,'tools/conformance/adapters/typed.mjs')};assert.equal(m.artifactKind,'derived-b1');fs.writeFileSync(path.join(out,'target.json'),JSON.stringify(target,null,2)+'\n');
const inputs=[import.meta.filename,process.execPath,workflow,processFile,selection,path.join(path.dirname(selection),'manifest.json'),path.join(root,'design/phase22/context-production-boundary.md'),...cases.filter(c=>c.file).map(c=>c.file),path.join(build,'attempt.json'),path.join(m.snapshot.root,'tools/conformance/target.mjs')].map(w.identity),report={kind:'phase22-context-paired-observations',complete:false,pass:false,cpu:3,api:m.api,attempt:w.identity(path.join(build,'attempt.json')),cache,inputs,scope:'Selected exact paired observations on an identity-verified genuine checked derivative. CPU3 override is runner-only; checked attempt and compiler bytes unchanged.'};const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');save();
try{
 const execution=await supervise('taskset',['-c','3',process.execPath,'--stack-size=4096','--max-old-space-size=4096',path.join(m.snapshot.root,'tools/conformance/target.mjs'),path.join(out,'target.json'),path.join(out,'selected')],{directory:path.join(out,'selected-command'),env,timeoutMs:900000});report.execution=execution;save();requireExecution(execution,[0,1]);
 const read=n=>JSON.parse(fs.readFileSync(path.join(out,'selected',n))),paired=read('paired.json'),reference=read('reference.json'),candidate=read('candidate.json');assert.ok(w.observationHealth(reference)&&w.observationHealth(candidate));assert.ok(!paired.error);assert.equal(paired.missing.length,0);assert.equal(paired.rows.length,cases.reduce((n,c)=>n+c.lanes.length,0));assert.deepEqual(paired.rows.map(r=>r.id+'@'+r.lane).sort(),cases.flatMap(c=>c.lanes.map(l=>c.id+'@'+l)).sort());
 report.selected={file:w.identity(path.join(out,'selected/paired.json')),selectedComplete:paired.selectedComplete,exactDifferences:paired.rows.filter(r=>!r.exactAgreement).length,discrepancies:paired.discrepancies,semanticDifferences:paired.rows.filter(r=>!r.semanticAgreement).length,strictDifferences:paired.rows.filter(r=>!r.exactAgreement).map(r=>({id:r.id,lane:r.lane,reference:r.reference,candidate:r.candidate})),reference:reference.summary,candidate:candidate.summary};
 await w.verifyAttempt(build);inputs.forEach(w.verifyIdentity);w.verifyIdentity(cache);report.complete=true;report.pass=paired.rows.every(r=>r.referenceVerdict==='pass'&&r.candidateVerdict==='pass'&&r.semanticAgreement&&r.exactAgreement);report.exactAgreement=paired.rows.every(r=>r.exactAgreement);report.passMeaning='Complete healthy observations with every explicit contract and all strict diagnostics matching the pin; no gap suppression.';
}catch(e){report.error=e.stack??String(e);process.exitCode=1;}
save();console.log(JSON.stringify({complete:report.complete,pass:report.pass,observations:report.selected?.candidate.probes,exactDifferences:report.selected?.exactDifferences,error:report.error}));
