#!/usr/bin/env python3
from pathlib import Path
import json,hashlib,collections
R=Path(__file__).resolve().parents[4];O=R/'selfhost/build/phase22/context-controls-do-baseline-01';I=R/'selfhost/build/phase22/context-controls-do-inputs-01'
def load(p):return json.loads(Path(p).read_text())
def identity(p):
 p=Path(p).resolve();b=p.read_bytes();return dict(file=str(p),sha256=hashlib.sha256(b).hexdigest(),bytes=len(b))
report=load(O/'report.json');paired=load(O/'selected/paired.json');plan=load(I/'plan.json');assert report['complete'] and report['pass'];assert len(paired['rows'])==20
for rec in report['inputs']+plan['inputs']+plan['fixtures']:assert identity(rec['file'])['sha256']==rec['sha256'],rec['file']
differences=[r for r in paired['rows'] if not r['exactAgreement']];assert len(differences)==3;assert all(not r['semanticAgreement'] for r in differences)
assert not [r for r in paired['rows'] if r['referenceVerdict']=='fail']
r={'kind':'phase22-independent-do-baseline','complete':True,'pass':True,'passMeaning':'Healthy complete baseline acquisition;17 exact and3 existing primitive differences retained. No migration candidate consumed.','parentApiSha256':report['api']['sha256'],'observations':20,'exact':17,'strictDifferences':3,'primitiveDifferences':3,'rawSelectedComplete':paired['selectedComplete'],'referenceVerdicts':dict(collections.Counter(x['referenceVerdict'] for x in paired['rows'])),'candidateVerdicts':dict(collections.Counter(x['candidateVerdict'] for x in paired['rows'])),'findings':[{'kind':'imported-monad-alias','observations':1,'actual':'Pinned check accepts; installed check refuses undefined Box.Id.bind. Both parse accept.','implication':'Generated bind/pure names must follow the actual header alias-resolution contract.'},{'kind':'malformed-rhs-failure-transport','observations':2,'actual':'Pinned parse/check lanes select expected term/observed closing paren; installed reports load-phase Invalid compiler source range.','implication':'A failed typed-bind RHS must preserve the selected parser error without leaking malformed intermediate ranges to host validation.'}],'rows':paired['rows'],'inputs':[identity(p) for p in [Path(__file__),I/'plan.json',I/'selection.json',O/'report.json',O/'selected/paired.json',O/'selected/reference.json',O/'selected/candidate.json']]+plan['inputs']+plan['fixtures'],'jobsClosed':True,'limitations':['These are pre-existing installed-parent defects and additional observed scope beyond the broader196 census; no candidate correction is claimed.','Original pin fixture negative parse lane is observed, not an oracle failure. No oracle or source fixture was edited.','Comments/parenthesized binder acceptance is public behavior evidence; structural source-span endpoints remain the implementation owner’s separate gate.']}
p=R/'implementation/phase22/context-controls-do-baseline.json';assert not p.exists();p.write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({'pass':True,'observations':20,'exact':17,'primitiveDifferences':3,'sha256':identity(p)['sha256']}))
