#!/usr/bin/env python3
import hashlib,json
from pathlib import Path
R=Path.cwd();o=R/'implementation/phase22/context-controls-feature-baseline.json';assert not o.exists()
def ident(p):
 p=(R/p).resolve();return {'file':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'bytes':p.stat().st_size}
roots={'feature40':'context-controls-feature-baseline-01','alias4':'context-controls-feature-alias-baseline-01','program12':'context-controls-feature-program-baseline-01'}
inputs=[ident(__file__),ident('selfhost/build/phase22/context-controls-feature-inputs-01/plan.json'),ident('selfhost/build/phase22/context-controls-feature-alias-inputs-01/plan.json')]; summaries={}
for name,d in roots.items():
 base='selfhost/build/phase22/'+d;r=json.loads((R/base/'report.json').read_text());p=json.loads((R/base/'selected/paired.json').read_text());assert r['complete'] and r['pass'];inputs += [ident(base+'/report.json'),ident(base+'/selected/paired.json')]
 summaries[name]={'observations':len(p['rows']),'exact':sum(x['exactAgreement'] for x in p['rows']),'rawSelectedComplete':p['selectedComplete'],'primitiveDifferences':[x['id']+'@'+x['lane'] for x in p['rows'] if not x['semanticAgreement']],'strictDifferences':[x['id']+'@'+x['lane'] for x in p['rows'] if not x['exactAgreement']],'prospectiveOracleFailures':[x['id']+'@'+x['lane'] for x in p['rows'] if x['referenceVerdict']=='fail'],'observedReference':[x['id']+'@'+x['lane'] for x in p['rows'] if x['referenceVerdict']=='observed']}
nspath='selfhost/build/phase22/context-controls-namespace-direct-01/report.json';ns=json.loads((R/nspath).read_text());assert ns['complete'] and ns['pass'] and ns['confirmedRangeMismatch'];inputs.append(ident(nspath))
report={'kind':'phase22-rewrite-array-independent-baseline-review','complete':True,'pass':True,'passMeaning':'Inputs frozen and baseline acquisition healthy; raw conformance failures and disproved prospective expectations retained. No production-candidate claim.','pin':'b2111cf43244e65f76ddc278ee695e669f720cbf','parentApi':'44094e58cb0ef033e2c08c2827565e859c3594b3136868d4f821262145aea7f0','controls':summaries,'overlap':'Program12 overlaps two fixtures already present in feature40; counts are separate lane observations, not56 distinct fixtures.','review':[
{'id':'namespace-let-first-error','finding':'The pre-fix contextual namespace Let branch rebuilt a Let around an Error. That concealed an earlier namespace failure from shallow callers and let an invalid array count or later index RHS override it. Pin recursively enters Let.f and throws. Baseline witness is array-namespace-before-count. Root reports a shared helper fix; future production outcomes must establish it.'},
{'id':'namespace-alias-cursor','finding':'The actual frozen f7dd372d helper fails at operator end85, while pin fails at delimiter end86 with observed space. Returned input has previousEnd86 and next-token begin87. A generic next-token begin is also incorrect here. Preserve original operator origin on success; use the exact semantic checkpoint cursor for alias failure.','reference':ns['reference'],'actual':{k:ns['actual'][k] for k in ['begin','end']},'grammarCursor':ns['actualGrammarCursor']},
{'id':'rewrite-scope','finding':'Inspection finds endpoint underscore and named evidence opened only for motive, both closed before body. Proof and motive failures are shallow-stopped before later children. New positive shadow program pins outer h survival; three negative neighbors freeze proof/motive/body ordering.'},
{'id':'array-count-representation','finding':'Pin accepts compact Nat plus explicit Succ/Zero counts, not bare U32. Parent wrongly accepts U32 and rejects explicit Succ; contextual f_array_nat_depth intentionally changes those results. Close precedes namespace, namespace precedes count.'},
{'id':'array-write-body','finding':'Pin term_write recognizes an exact four-argument Array.set with a Var array argument and parse_more before opening its implicit binding. New written-call program pins output9. Raw parent rejects it; nonvariable-array neighbor must retain no-binding behavior.'}], 'incorrectProspectiveExpectations':{'count':2,'retained':True,'explanation':'The original good-RHS alias fixture had no alias member add; pin correctly fell back to global U32.add and accepted both parse/check. Original expectations are preserved. Separate alias4 declares words.add, so both qualified and global names exist and pin refuses before either RHS.'},'privateProbeScope':'Appended internal export preserves the genuine f7dd372d API prefix. It is a bounded direct helper witness, not the released public API. It consumes actual parsed prior definitions and real FContextual scope.','inputs':inputs,'sourceEdits':False}
o.write_text(json.dumps(report,indent=2)+'\n');o.with_suffix('.md').write_text('''# Phase22 rewrite and array baseline

Frozen feature40 has 29 exact observations; alias4 has zero; program12 has eight. All acquisitions are healthy. Raw failures and two incorrect prospective alias expectations remain unchanged. Programs cover rewrite shadow restoration (7), a written Array.set statement (9), and existing nested index writes (34). Only the written-call program differs in all four parent lanes.

Two code findings require contextual integration checks. First, a namespace Error under a completed Let must be returned shallowly before checking array count or an index RHS. The pinned `[(x = 1; x + 1) : 0*3n]` witness reports the namespace error; the raw parent reports the later count error. Root has prepared a shared helper correction. Second, the actual frozen namespace helper puts an alias failure at operator end85; pin points at86, the space immediately after `]`. The next token starts at87. `previousEnd` is the correct cursor for this delimiter checkpoint, with the original operator origin preserved on success.

The pinned count reader accepts Nat literals and explicit Succ/Zero chains, refuses U32 counts, and checks closing delimiter before namespace and count. Parent behavior differs on U32 and Succ. The new fixtures preserve those outcomes for the real production route. Rewrite inspection confirms motive-only endpoint/evidence scope, restoration before body, and shallow proof/motive failure stops. The actual future image still needs all frozen public controls.

The original alias-good-RHS fixture lacked a module `add`, so the pin legitimately fell back to global U32.add and accepted it. Both mistaken refusal expectations are preserved. A separate four-observation cohort declares that module member; pin then reports ambiguity immediately after `]` before both valid and invalid RHS neighbors. No oracle or fixture was rewritten.

The JSON binds the baseline selections/results and the direct private witness. No compiler source was edited. This report claims baseline closure and review findings only; production candidate controls are separate.
''');print(json.dumps({'complete':True,'report':ident(str(o.relative_to(R))),'controls':{k:[v['exact'],v['observations']] for k,v in summaries.items()}}))
