#!/usr/bin/env python3
from pathlib import Path
import hashlib,json
R=Path.cwd();out=R/'implementation/phase22/context-controls-finalization-review.json';assert not out.exists()
def ident(p):
 p=(R/p).resolve();b=p.read_bytes();return {'file':str(p),'sha256':hashlib.sha256(b).hexdigest(),'bytes':len(b)}
inputs=[ident(__file__),ident('selfhost/build/phase22/context-frontend-01-raw-triage.json'),ident('selfhost/.bootstrap/upstream-phase8/bend2/bend.ts'),ident('selfhost/build/phase22/context-source-05/project/src/front/contextual.bend'),ident('selfhost/build/phase22/context-source-05/project/src/front/families.bend'),ident('selfhost/build/phase22/context-source-05/project/src/front/literals_arrays.bend'),ident('selfhost/build/phase22/context-source-05/project/src/front/fresh_work.bend')];groups={}
for key,name in [('finalization26','finalization'),('doHeader4','do-header'),('signatureDemand2','header-demand')]:
 base='selfhost/build/phase22/context-controls-'+name+'-baseline-01';d=json.loads((R/base/'report.json').read_text());p=json.loads((R/base/'selected/paired.json').read_text());assert d['complete'] and d['pass'];assert not any(x['referenceVerdict']=='fail' for x in p['rows']);groups[key]={'observations':len(p['rows']),'exact':sum(x['exactAgreement'] for x in p['rows']),'rawSelectedComplete':p['selectedComplete'],'prospectiveOracleFailures':0,'strictDifferences':[x['id']+'@'+x['lane'] for x in p['rows'] if not x['exactAgreement']]};inputs.extend([ident(base+'/report.json'),ident(base+'/selected/paired.json'),ident('selfhost/build/phase22/context-controls-'+name+'-inputs-01/plan.json'),ident('selfhost/build/phase22/context-controls-'+name+'-inputs-01/selection.json')])
report={'kind':'phase22-implicit-operator-checkpoint-independent-review','complete':True,'pass':True,'passMeaning':'Cause audit and frozen baseline acquisition closed; no corrected-production claim.','pin':'b2111cf43244e65f76ddc278ee695e669f720cbf','groups':groups,'overlap':'SignatureDemand2 reuses the parameterized header parse fixture from Finalization26. Do not count32 as distinct programs.','cause':{'implicitOperator':'Pin term_higher rejects Ref precisely when lastIndexOf(dot)==0. Source05 FCompleted bypasses f_scope_reference/f_operator_error and its common freshener has no corresponding refusal. Body parse_def explicitly higher/lower/higher materializes after flattening before advancing declarations.','relativeImport':'Source05 namespace predicate accepted every leading dot. Pin requires its last dot to be that first dot; ../lib/math.value is a canonical ordinary name and must not be prefixed by the operator type namespace.','demandBoundary':'Header term_higher forces immediate Ref/App and All domain, but leaves All codomain and Lam body deferred. App can apply a converted Lam and expose its body. A full eager header scan and a blanket skip of every Lam body both differ from the pin. Body finalization includes term_lower, which forces all binder children.','doHeader':'Pin consumes <, resolves the monad name, then parses arguments. Real loaded alias ambiguity must precede malformed arguments. Compact <> error points at the >, not after it.'},'confirmedWitnesses':['Completed body1+2 followed by later top-level) reports operator error first.','Parameter-wrapped Unit+Unit header followed by later) reports top-level) first; installed parent has inherited two-lane discrepancy.','Zero-parameter Unit+Unit header followed by later) reports header operator first.','Legal 1+(2*3) inside outer U32 annotation stays accepted; do not refuse unresolved operators at every nested group.','Marked +x after astral comment retains negative-index diagnostic and two-character span on parent.','Relative imported M.value inside arithmetic annotation resolves normally on parent and pin.','Ambiguous Box.Id<)> and Box.Id<> report ambiguity at immediate post-< cursor, observing ) and > respectively.'],'limitations':['The erased-local-use fixture fails earlier literal inference in both pin and parent; it does not independently prove erased-binder usage or marker-span behavior.','Main full2996 triage is an explicitly labeled raw root triage, not a replacement for strict target-manifest audit.','No compiler source changes or builds were made by this owner; corrected candidate reruns remain pending.'],'jobsClosed':True,'inputs':inputs}
out.write_text(json.dumps(report,indent=2)+'\n');out.with_suffix('.md').write_text('''# Implicit operator and parser checkpoint review

The unresolved-operator regressions have a concrete missing owner. Pinned `term_higher` rejects a Ref exactly when its final dot is the initial dot. The new completed roots bypass the old `f_scope_reference` operator check, and the freshener does not replace it. This check belongs at materialization after applicable namespace annotations, not at every nested group: an outer annotation may still resolve a nested operator.

Header and body demand differ. `parse_def` materializes a flattened body through higher/lower/higher before parsing a later declaration. A header only enters higher form, which defers All codomains and Lam bodies. Applied lambdas can be forced by higher's App branch. The frozen pair proves the practical difference: zero-parameter `Unit + Unit` fails at the header operator; the same return type behind a parameter remains deferred and a later top-level `)` wins. A full eager header scan would introduce a new error-order discrepancy. The installed parent already has that discrepancy in the parameterized witness, and it is preserved.

The relative-import regression uses the same predicate distinction. A name such as `../lib/math.value` begins with a dot but its last dot is later; the pin leaves it unchanged. The source05 namespace predicate incorrectly prefixes it as an implicit operator. An independent safe relative-import program avoids the unrelated unsafe-proof status of the reused upstream witness.

Do-header alias lookup is another distinct checkpoint: after consuming `<`, resolve the monad before parsing arguments. Two genuinely loaded declarations make `Box.Id` ambiguous. The pin observes `)` in the malformed-argument neighbor and `>` in compact `<>`, both immediately after `<`.

All new baseline acquisitions are closed: finalization26 has 24 exact observations; do-header4 has none; signature-demand2 has one. No prospective oracle failures occurred. Signature-demand2 reuses one parse fixture from finalization26. The marked astral-comment control preserves the written `+x` range; the erased-local control fails earlier literal inference and is not claimed as an erased-use/span proof. Exact corrected-candidate reruns remain separate.
''');print(json.dumps({'complete':True,'pass':True,'report':ident(str(out.relative_to(R))),'groups':groups}))
