// Public checked program completion on parsed controls; no private exports/rebuild.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';
const root=path.resolve(import.meta.dirname,'../../../..'),build=fs.realpathSync(process.argv[2]),out=path.resolve(process.argv[3]),controlRoot=fs.realpathSync(process.argv[4]);fs.mkdirSync(out);
const w=await import(pathToFileURL(path.join(build,'snapshot/tools/development/workflow.mjs'))),m=await w.verifyAttempt(build),cache=w.validatedCache(path.join(m.snapshot.root,'build/typed/cache'),m.api.file,m.base.file);
const expected={'repeat-key':['first~0','first~1'],'interleaved-keys':['first~0','first~1','second~0','second~1'],'nested-templates':['first~0','outer~0'],'decreasing-reuse':['loop~0'],'erased-call':[],'same-lambda':['apply~0'],'renamed-lambda':['apply~0','apply~1'],'lambda-quantities':['apply~0','apply~1']};
const cases=Object.entries(expected).map(([name,instances])=>({name,instances,file:path.join(controlRoot,'fixtures',name+'.bend')})),tsFile=path.join(root,'selfhost/.bootstrap/upstream-phase8/bend2/bend.ts'),hostFile=path.join(m.snapshot.root,'tools/typed-driver.mjs');
for(const k of Object.keys(process.env))if(k.startsWith('BEND_')||['NODE_OPTIONS','NODE_PATH'].includes(k))delete process.env[k];Object.assign(process.env,{BEND_TYPED_API:m.api.file,BEND_BASE:m.base.file,BEND_TYPED_RUNTIME:m.runtime.file});
const inputs=[import.meta.filename,m.api.file,m.base.file,cache.file,tsFile,hostFile,path.join(controlRoot,'manifest.json'),...cases.map(c=>c.file)].map(w.identity),report={kind:'phase17-live-instance-memo-controls',complete:false,pass:false,inputs,api:m.api,rows:[],scope:'Public checker ABI2 program-completion book compared with pinned TypeScript book_valid; complete materialized instance-name sets, separate from paired diagnostics.'};
const save=()=>fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2)+'\n');save();
try{const a=(await import(pathToFileURL(m.api.file))).default,B=await import(pathToFileURL(tsFile)),host=await import(pathToFileURL(hostFile)),seed={...JSON.parse(fs.readFileSync(cache.file)),sourceText:fs.readFileSync(m.base.file,'utf8')};assert.equal(a.compiler_check_result_abi(),2);
for(const c of cases){const row={name:c.name,expected:c.instances};report.rows.push(row);try{const b=B.book_nil();await B.book_load(b,c.file,'',new Map());B.book_valid(b);row.reference=Object.keys(b.tlds).filter(n=>/~\d+$/.test(n)).sort();assert.deepEqual(row.reference,row.expected);const graph=host.discoverSources(a,c.file,{seed}),loaded=a.f_load_graph_seed(graph.main,graph.sources,seed.sourcePath,seed.sourceText,seed.book);assert.equal(loaded.error,'');const checked=a.check_program_diagnostic(loaded.book,{$:'Nil'},{$:'Nil'});assert.equal(checked.error,'');const names=[];for(let p=checked.book;p.$==='Con';p=p.tail)if(/~\d+$/.test(p.head.name))names.push(p.head.name);row.candidate=names.sort();row.exact=JSON.stringify(row.reference)===JSON.stringify(row.candidate);}catch(e){row.error=e?.$==='Err'?B.err_show(e):e.stack??String(e);}save();}
inputs.forEach(w.verifyIdentity);await w.verifyAttempt(build);report.complete=true;report.pass=report.rows.every(r=>r.exact);if(!report.pass)process.exitCode=1;
}catch(e){report.error=e.stack??String(e);process.exitCode=1;}save();console.log(JSON.stringify({complete:report.complete,pass:report.pass,rows:report.rows.length,failures:report.rows.filter(r=>!r.exact).map(r=>r.name),error:report.error}));
