import pathlib,json,hashlib,datetime
r=pathlib.Path.cwd();o=r/'selfhost/build/phase14/laws-final-audit-01';o.mkdir();paths=['selfhost/build/phase14/laws-candidate-04/attempt/validation-001/report.json','selfhost/build/phase14/laws-controls-04/candidate04/validation/selected/paired.json','selfhost/build/phase14/laws-extra-controls-02/candidate04/validation/selected/paired.json','selfhost/build/phase14/laws-api-controls-01/controls/report.json'];docs=[json.loads((r/p).read_text())for p in paths];focused,main,extra,api=docs;assert focused['complete']and focused['pass'];rows=main['rows']+extra['rows'];assert len(rows)==50;assert all(x['semanticAgreement']for x in rows)
strict=[x['id']for x in rows if x['candidateVerdict']=='fail'];assert sorted(strict)==['p14-existing-alias_decl','p14-existing-alias_shadow','p14-existing-alias_twice'];trust=[x for x in main['rows']if x['reference']['phase']=='verdict'];assert len(trust)==11;assert all(x['exactAgreement']for x in trust);target=[x for x in main['rows']if 'unsafe_law_'in x['id']];assert len(target)==8;assert all(x['exactAgreement']for x in target);templates=[x for x in main['rows']if 'template-trust'in x['id']];assert len(templates)==4;assert all(x['exactAgreement']for x in templates)
for x in templates:
 if x['lane']=='check':assert x['candidate']['unsafeDefinitions']==['bad','choose','main']and x['candidate']['proofTrust']=='failed'and x['candidate']['typeAccepted']and x['candidate']['checked']and x['candidate']['status']=='ok'and x['candidate']['exitCode']==0
assert api['complete']and api['pass']and len(api['rows'])==6;assert all(len(x['outputs'])==4 for x in api['rows']);assert all(len(set(y['sha256']for y in x['outputs']))==1for x in api['rows'])
for path in ['selfhost/build/phase14/laws-controls-04/candidate04/launcher.json','selfhost/build/phase14/laws-extra-controls-02/candidate04/launcher.json','selfhost/build/phase14/laws-api-controls-01/launcher.json']:
 d=json.loads((r/path).read_text());e=d['execution'];assert d['complete']and not e['error']and not e['signal']and not e['timedOut']and not e['overflow']and e['exitCode']in[0,1]
manifest=json.loads((r/'selfhost/build/phase14/laws-candidate-04/attempt/attempt.json').read_text());patch=json.loads((r/'selfhost/build/phase14/laws-candidate-04/patch-manifest.json').read_text())
for x in patch['files']:
 assert hashlib.sha256((r/'selfhost/build/phase14/laws-candidate-04/project'/x['file']).read_bytes()).hexdigest()==x['afterSha256']
 assert hashlib.sha256((r/'selfhost'/x['file']).read_bytes()).hexdigest()==x['beforeSha256']
inputs=[{'file':str(r/p),'sha256':hashlib.sha256((r/p).read_bytes()).hexdigest()}for p in paths]
report={'kind':'phase14-laws-final-audit','complete':True,'scopedSemanticPass':True,'strictMainHarnessPass':main['selectedComplete'],'knownStrictFailures':strict,'pairedObservations':len(rows),'semanticDifferences':0,'exactDifferences':sum(not x['exactAgreement']for x in rows),'fourTargetObservationsExact':len(target),'priorTrustCasesExact':len(trust),'templateRowsExact':len(templates),'apiResultFamilies':len(api['rows']),'apiVariantsPerFamily':4,'focusedCases':22,'api':manifest['api'],'checkedApi':manifest['checkedApi'],'inputs':inputs,'patch':patch,'scope':'Not broad conformance or a benchmark. Main paired strict result remains failed for three alias diagnostics; no oracle is weakened. Imported targets and template trust are required exact.','finished':datetime.datetime.now(datetime.timezone.utc).isoformat()};(o/'report.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps({k:report[k]for k in ['complete','pairedObservations','semanticDifferences','exactDifferences','fourTargetObservationsExact','priorTrustCasesExact','templateRowsExact','api']}))
