from pathlib import Path
import json,hashlib,datetime,statistics
R=Path('/home/ai/bend2/build/publish/bend');B=R/'selfhost/build/phase28';O=R/'implementation/phase28'
a=json.loads(Path('/tmp/phase28-audit-timing-01-final.json').read_text());b=json.loads(Path('/tmp/phase28-audit-timing-long-01-final.json').read_text())
assert a['status']==b['status']=='PASS' and a['complete'] and b['complete']
identities={};artifacts={};cross=0
for x in [a,b]:
 for field,target in [('identities',identities),('rawArtifacts',artifacts)]:
  for v in x[field]:
   if v['file'] in target:assert v==target[v['file']];cross+=1
   target[v['file']]=v
intervals=[]
for x in [a,b]:
 for p in x['processes']:
  if 'directory' in p:
   v=json.loads((Path(p['directory'])/'launch.json').read_text());start=v['started'];finish=start+v['processSeconds']
  else:
   v=json.loads(Path(p['label']).read_text());start=v['started'];finish=v['finished']
  intervals.append({'label':p['label'],'started':start,'finished':finish})
intervals.sort(key=lambda r:r['started'])
for one,two in zip(intervals,intervals[1:]):assert one['finished']<=two['started']+.005;cross+=1
ar=json.loads((B/'application-timing-01/report.json').read_text());lr=json.loads((B/'timing-long-01/report.json').read_text());tr=json.loads((B/'timing-01/report.json').read_text())
long_start=min(r['started'] for c in lr['cases'] for rows in [c['checks'].values(),c['calibration'].values(),c['samples']] for r in rows)
app_end=max(r['finished'] for r in ar['samples']);assert app_end<long_start;cross+=1
orig_end=max(r['started']+r['processSeconds'] for c in tr['cases'] for rows in [c['checks'].values(),c['calibration'].values(),c['samples']] for r in rows)
assert orig_end<min(r['started'] for r in ar['samples']);cross+=1
stamp=datetime.datetime.fromisoformat('2026-09-30T05:17:24.487553+00:00').timestamp();assert stamp<long_start;cross+=1
byid={c['id']:c for c in a['library']};comparison=[]
for c in b['library']:
 old=byid[c['id']];assert c['args']==old['args'] and c['expected']==old['expected'];cross+=1
 row={'id':c['id'],'originalWarmedRatio':old['selfhostOverUpstreamWarmed'],'longWarmedRatio':c['selfhostOverUpstreamWarmed'],'ratioChangePercent':100*(c['selfhostOverUpstreamWarmed']/old['selfhostOverUpstreamWarmed']-1),'selfhostHalves':{}}
 for name,z in [('original',old),('long',c)]:
  vals=[v['secondOverFirstPerCall'] for v in z['sides']['selfhost']['halves']]
  row['selfhostHalves'][name]={'min':min(vals),'max':max(vals),'beyondTenPercent':sum(v<.9 or v>1.1 for v in vals),'samples':len(vals)}
 comparison.append(row)
windows=[]
for v in [a,b]:windows.append({k:x for k,x in v.items() if k not in ['identities','rawArtifacts','sourcePreservation','acquisitionOutcomes','processes']})
out={'kind':'phase28-independent-combined-measurement-audit','complete':True,'status':'PASS','auditedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'windowChecks':a['checks']+b['checks'],'crossChecks':cross,'failures':[],'counts':{'libraryTimingSamples':140,'libraryChecks':28,'libraryCalibrations':28,'applicationTimingSamples':10,'allProcesses':206,'rawLaunchStdoutStderrFiles':618},'method':'Read-only reconstruction from every launch, raw stdout/stderr, frozen config, emission receipt and source/module/host identity. No emitted program, compiler or benchmark was executed by this reviewer.','windows':windows,'warmupComparison':comparison,'crossCampaignOrder':{'originalLibraryEnd':orig_end,'applicationEnd':app_end,'followupStart':long_start,'followupPlanTimestamp':stamp,'noObservedChildOverlap':True},'sourcePreservation':a['sourcePreservation'],'acquisitionOutcomes':a['acquisitionOutcomes'],'identities':list(identities.values()),'artifacts':list(artifacts.values()),'processes':a['processes']+b['processes'],'auditScriptSha256':hashlib.sha256(Path('/tmp/audit-phase28.py').read_bytes()).hexdigest()}
(O/'measurement-audit.json').write_text(json.dumps(out,indent=2)+'\n')
lines=['# Phase28 independent measurement audit','',f"**PASS.** Independently reconstructed all 206 processes: 140 library timing samples, 28 checks, 28 calibrations and 10 complete application processes. All {a['checks']+b['checks']:,} window checks and {cross:,} cross-window checks pass. No generated program or compiler was executed by this reviewer; this audit reads the saved raw evidence.",'','The [machine-readable audit](measurement-audit.json) records identities, every sample, recomputed medians/ranges/ratios, calibration counts, timed halves and preserved acquisition outcomes. No timing sample was removed or replaced.','', '## Checks performed','', '- Matched every report row to its raw launch JSON and stdout; checked empty stderr, successful exits, deadlines, Node binary identity, stack/heap flags and CPU3 affinity reported by every library child. Complete application launches use the recorded CPU3 taskset command; they do not instrument affinity internally.', '- Verified exact arguments, complete first results, every timed/calibration checksum, fixed repetitions per variant, calibration doubling/stopping rules and the 300ms target formula. Recomputed all median/minimum/maximum values and both first-call and warmed ratios from raw values. First-call summaries use the five timing processes per variant, separately from check/calibration processes.', '- Verified original warmup floors of three calls AND one second, follow-up floors of 100 calls AND three seconds, and that subprocess wall time covers the recorded import, first-call, warmup and measured work. A target duration is not a hard duration floor; expensive calls use one repetition, so those samples cannot provide two halves.', '- Verified source bytes against pinned Git objects, appended wrappers, unchanged mixed tests/application, checked emission receipts, output/module hashes, Base, compiler API/runtime/driver and host identities. Follow-up configurations and emitted bytes match their original cases. The derived runner and launcher equal the prescribed byte transformations exactly.', '- Found all planned launch directories and all 618 launch/stdout/stderr files. Every child interval is disjoint in the recorded campaigns; the original libraries finish before the application, which finishes before the follow-up. This is evidence of serial execution, not proof of isolation from unrelated machine activity.', '', '## Warmup sensitivity remains visible','', 'The follow-up was planned after the first nine cases, selecting all four with repeated greater-than-10% changes between timed halves. It preserves the original measurements. These are results after specified warmup windows, not demonstrated steady-state throughput. Five observations and observed ranges do not constitute statistical confidence intervals.','', '| Case | Original selfhost/upstream | Longer warmup | Candidate second-half / first-half, original | Candidate second-half / first-half, longer |','|---|---:|---:|---:|---:|']
for c in comparison:
 x=c['selfhostHalves']['original'];y=c['selfhostHalves']['long']
 lines.append(f"| {c['id']} | {c['originalWarmedRatio']:.2f}× | {c['longWarmedRatio']:.2f}× | {x['min']:.3f}–{x['max']:.3f} | {y['min']:.3f}–{y['max']:.3f} |")
lines+=['', 'Ratios between halves divide their per-call costs, including unequal half lengths. Longer warmup removes the greater-than-10% flag from all Mandelbrot samples. Bitonic retains a 10.7–14.3% slower second half in all five samples; morning retains one 14.5% faster second half; Map/Set changes direction, with all five second halves 12.7–17.5% faster. The phase changes are measured observations; this audit does not assign them individually to JIT compilation, garbage collection or another cause. The performance deficit remains large under both protocols.', '', '## Distinct execution boundaries','', 'The original ten library pairs all return their frozen expected complete scalar or string values. Their first-call ratios and warmed ratios are deliberately separate. Emission acquisition times are descriptive and excluded from these runtime comparisons; none of these runs measures self-emitted compiler H throughput.','', f"The HVM mini application has exactly matching 42-byte stdout in all ten fresh processes. Its median whole-process time is {a['application']['sides']['upstream']['median']*1000:.4f}ms upstream and {a['application']['sides']['selfhost']['median']*1000:.4f}ms selfhost, a {a['application']['selfhostOverUpstream']:.6f}× ratio. That includes startup, the respective CommonJS/ESM loader, computation, output and exit. Emitted bytes are unchanged when the upstream host filename is corrected to `.cjs`. The printed normal form agrees with the embedded-program description; the 79-interaction count remains a differential oracle.",'', 'The two rejected raytrace wrapper attempts and the original HVM host-extension failure remain visible as acquisition outcomes (five failed variant processes across three failed attempts). Final paired inputs cover all eleven selected programs; there is no survivor-only aggregate. Benchmark checksums are the programs’ full observable outputs, not independent validation of every internal pixel or collection element. Tiny mixed tests, the Mandelbrot strip and fixed raytrace probe traversal retain their documented scope. This audit supports publishing the bounded comparison with its ranges and warmup caveats; it does not renew the full conformance inventory or claim a universal production-program ratio.','']
(O/'measurement-audit.md').write_text('\n'.join(lines))
print(json.dumps({'checks':out['windowChecks'],'crossChecks':cross,'bytes':(O/'measurement-audit.json').stat().st_size,'comparison':comparison},indent=2))
