import pathlib,shutil,json,hashlib,difflib
root=pathlib.Path.cwd();base=root/'selfhost';old=base/'build/phase15/behavior-source-02/project';out=base/'build/phase15/behavior-source-03';out.mkdir();project=out/'project'
for name in ['src','tools','tests/frontend/phase2-rules']:shutil.copytree(old/name,project/name)
(project/'dist').mkdir()
def replace(s,a,b):assert s.count(a)==1,(a,s.count(a));return s.replace(a,b)
p=project/'src/load/imports.bend';s=p.read_text();s=replace(s,'def f_import_missing(+source: String, +im: KTerm, +path: String) -> String:','def f_import_failure(+source: String, +im: KTerm, +path: String, +cycle: Bool) -> String:');s=replace(s,'  "Error:\\n- message  : no such file: " ++ path ++ "\\nLocation:" ++ dg_snippet(DSpan{source, offset, offset})','  "Error:\\n- message  : " ++ f_choose(String, cycle, u => "an import cycle through ", u => "no such file: ") ++ path ++ "\\nLocation:" ++ dg_snippet(DSpan{source, offset, offset})');p.write_text(s)
p=project/'tools/typed-driver.mjs';s=p.read_text().replace('f_import_missing','f_import_failure');s=replace(s,'const sources=[],seen=new Map(),physical=new Map(),foreign=new Map();','const sources=[],seen=new Map(),physical=new Map(),foreign=new Map(),active=new Set();')
s=replace(s,'    const absolute=fs.realpathSync(file);\n    if(seen.has(name)) {',"    const absolute=fs.realpathSync(file);\n    // Stop an active canonical IO traversal before later imports or body errors.\n    if(active.has(absolute)&&api.f_import_failure)\n      throw Object.assign(Error('Import traversal reentry'),{code:'BEND_IMPORT_CYCLE',importPath:absolute});\n    if(seen.has(name)) {")
s=replace(s,'    physical.set(absolute,parsed);','    physical.set(absolute,parsed);\n    active.add(absolute);')
s=replace(s,"        if(error.code==='ENOENT'&&!error.phase&&api.f_import_failure)\n          throw Object.assign(Error(api.f_import_failure(source,item,importedFile)),{phase:'parse',sourceFile:absolute});", "        if(!error.phase&&api.f_import_failure&&(error.code==='ENOENT'||error.code==='BEND_IMPORT_CYCLE'))\n          throw Object.assign(Error(api.f_import_failure(source,item,error.code==='BEND_IMPORT_CYCLE'?error.importPath:importedFile,error.code==='BEND_IMPORT_CYCLE')),{phase:'parse',sourceFile:absolute});")
s=replace(s,'    // Upstream loads earlier imports before it parses this module\'s body.','    active.delete(absolute);\n    // Upstream loads earlier imports before it parses this module\'s body.');p.write_text(s)
changes=[]
for name in ['src/front/sugar.bend','src/front/declarations.bend','src/front/validate.bend','src/load/imports.bend','tools/typed-driver.mjs']:
 before=(base/'build/phase14/combined-01/snapshot'/name).read_text();after=(project/name).read_text();changes.append({'file':name,'beforeSha256':hashlib.sha256(before.encode()).hexdigest(),'afterSha256':hashlib.sha256(after.encode()).hexdigest(),'physicalLineDelta':len(after.splitlines())-len(before.splitlines()),'byteDelta':len(after.encode())-len(before.encode())});(out/(name.replace('/','_')+'.patch')).write_text(''.join(difflib.unified_diff(before.splitlines(True),after.splitlines(True),fromfile=name,tofile=name)))
(out/'manifest.json').write_text(json.dumps({'kind':'phase15-cycle-order-candidate','changes':changes,'plan':str(root/'experiments/phase15/P15-005-import-cycle-order.md'),'tool':str(pathlib.Path(__file__).resolve()),'toolSha256':hashlib.sha256(pathlib.Path(__file__).read_bytes()).hexdigest()},indent=2)+'\n');(out/'config.json').write_text(json.dumps({'project':str(project),'upstream':str(base/'.bootstrap/upstream-phase8'),'profile':'equality','cpu':'2','jobs':1},indent=2)+'\n');print(out)
